# Generated by Django 4.1 on 2025-02-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0002_remove_usuario_perfis_delete_perfil"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="usuario",
            name="perfis",
            field=models.ManyToManyField(to="cadastros.perfil"),
        ),
    ]
