# Generated by Django 4.1 on 2025-02-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0004_alter_usuario_perfis"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="servicos",
            field=models.ManyToManyField(
                blank=True, related_name="funcionarios", to="cadastros.servico"
            ),
        ),
    ]
